[package]
name = "pins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buf_read_splitter = { path = "../_libs/buf_read_splitter" }